/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package t3;

/**
 *
 * @author User001
 */
public class FrameAgregarProducto extends javax.swing.JFrame {

    private FrameInicio padre;
    public FrameAgregarProducto(FrameInicio padre) {
        initComponents();
        this.padre =padre;
    }

    private FrameAgregarProducto() {
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblAgregarProducto = new javax.swing.JLabel();
        bttAgregarProducto = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        bttRetroceder = new javax.swing.JButton();
        lblTiendaMiguelito = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMarca.setText("Escribir Marca del Producto");
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 350, -1));

        txtPrecio.setText("Escribir precio del producto");
        txtPrecio.setMaximumSize(new java.awt.Dimension(200, 200));
        txtPrecio.setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 350, -1));

        lblAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarProducto.setText("Agregar Producto");
        getContentPane().add(lblAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        bttAgregarProducto.setText("Agregar");
        bttAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(bttAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtNombre.setText("Escribir Nombre del Producto");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 350, -1));

        bttRetroceder.setText("Retroceder");
        bttRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(bttRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        lblTiendaMiguelito.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTiendaMiguelito.setForeground(new java.awt.Color(255, 255, 255));
        lblTiendaMiguelito.setText("Tienda Miguelito");
        getContentPane().add(lblTiendaMiguelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t3/electrodomesticos.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRetrocederActionPerformed
        this.dispose();
       padre.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bttRetrocederActionPerformed

    private void bttAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarProductoActionPerformed
          this.dispose();
       padre.setVisible(true);  
    }//GEN-LAST:event_bttAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregarProducto;
    private javax.swing.JButton bttRetroceder;
    private javax.swing.JLabel lblAgregarProducto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTiendaMiguelito;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
