
package t3;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author User001
 */
public class FrameInicio extends javax.swing.JFrame {

     private static FrameInicio instancia;
     DefaultListModel model = new DefaultListModel();
     List<Producto> producto = new ArrayList<>();
    public FrameInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaProducto = new javax.swing.JLabel();
        bttIrAgregarProd = new javax.swing.JButton();
        bttIrCalculadora = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProducto = new javax.swing.JList<>();
        lblTiendaMiguelito = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListaProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblListaProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblListaProducto.setText("ListaProducto");
        getContentPane().add(lblListaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, -1));

        bttIrAgregarProd.setText("Agregar");
        bttIrAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIrAgregarProdActionPerformed(evt);
            }
        });
        getContentPane().add(bttIrAgregarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        bttIrCalculadora.setText("Calculadora");
        bttIrCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIrCalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(bttIrCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        lstProducto.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 360, 180));

        lblTiendaMiguelito.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTiendaMiguelito.setForeground(new java.awt.Color(255, 255, 255));
        lblTiendaMiguelito.setText("Tienda Miguelito");
        getContentPane().add(lblTiendaMiguelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t3/electrodomesticos.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttIrAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIrAgregarProdActionPerformed
    FrameAgregarProducto ventanacurso = new FrameAgregarProducto(this);
    ventanacurso.setVisible(true);
    this.setVisible(false);

    }//GEN-LAST:event_bttIrAgregarProdActionPerformed

    private void bttIrCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIrCalculadoraActionPerformed
        FrameCalculadora ventanacurso = new FrameCalculadora(this);
    ventanacurso.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_bttIrCalculadoraActionPerformed

     public void agregarProducto(String nombre, double precio, String marquin) {
        Producto nuevoProducto = new Producto(nombre, precio, marquin);
        producto.add(nuevoProducto);
        model.addElement(nuevoProducto);
        lstProducto.setModel(model);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttIrAgregarProd;
    private javax.swing.JButton bttIrCalculadora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblListaProducto;
    private javax.swing.JLabel lblTiendaMiguelito;
    private javax.swing.JList<String> lstProducto;
    // End of variables declaration//GEN-END:variables
}
