/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package t3;

/**
 *
 * @author User001
 */
public class FrameCalculadora extends javax.swing.JFrame {

    private FrameInicio padre;
    public FrameCalculadora(FrameInicio padre) {
        initComponents();
        this.padre=padre;
    }

    private FrameCalculadora() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCalculadora1 = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        bttSumar = new javax.swing.JButton();
        bttRetroceder = new javax.swing.JButton();
        lblTiendaMiguelito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSumaProd = new javax.swing.JList<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCalculadora1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCalculadora1.setForeground(new java.awt.Color(255, 255, 255));
        lblCalculadora1.setText("Resultado");
        getContentPane().add(lblCalculadora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        lblCalculadora.setText("Calculadora");
        getContentPane().add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        bttSumar.setText("+");
        bttSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSumarActionPerformed(evt);
            }
        });
        getContentPane().add(bttSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 50, -1));

        bttRetroceder.setText("Retroceder");
        bttRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(bttRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        lblTiendaMiguelito.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTiendaMiguelito.setForeground(new java.awt.Color(255, 255, 255));
        lblTiendaMiguelito.setText("Tienda Miguelito");
        getContentPane().add(lblTiendaMiguelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lstSumaProd.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSumaProd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t3/electrodomesticos.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRetrocederActionPerformed
        this.dispose();
       padre.setVisible(true);
    }//GEN-LAST:event_bttRetrocederActionPerformed

    private void bttSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttSumarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttRetroceder;
    private javax.swing.JButton bttSumar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblCalculadora1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTiendaMiguelito;
    private javax.swing.JList<String> lstSumaProd;
    // End of variables declaration//GEN-END:variables
}
